services:
  db:
    image: mysql:8.0.33
    #Macbook m1を使用しているためplantformを指定
    platform: linux/amd64
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: guarana
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306

  db2:
    image: mysql:8.0.33
    #Macbook m1を使用しているためplantformを指定
    platform: linux/amd64
    container_name: migration_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma-pass
      MYSQL_DATABASE: prisma
      TZ: "Asia/Tokyo"
    volumes:
      - migration-data:/var/lib/mysql
    ports:
      - 3308:3306

  backend:
    image: node:18-slim
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm ci && npx tsc && npm start"
    ports:
      - 3000:3000
    depends_on:
      - db
    #URLはlocalhostではなく、docker-composeで指定しているservicesのdbを指定
    environment:
      DATABASE_URL: mysql://user:pass@db:3306/guarana

volumes:
  db-data:
  migration-data:
